[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qp5eqyc4k246jlkuzxzdrprla92e7p0urccuyjr7y096grgj7eydct4lxdu"]

[[validator_account]]
address = "tnam1qyx57588ejm4ltfldr4kvftmcr8plkx7eykxkmsj"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.03"
net_address = "0.0.0.0:26656"

[validator_account.consensus_key]
pk = "tpknam1qrmn28v97n32lfmnpqrggy0xrampu42j6yyf4rc38jlmda3928y2uczxx8n"
authorization = "signam1qrqxcnak5x65q2jjumm6yrvye8dxdthurmp389gefsxas9zt8l0lm4p36z0dl2xr2azpfe9kuczp4ugkcu2vdnhw3xfudcl2fd2knuc95vffva"

[validator_account.protocol_key]
pk = "tpknam1qzr74rgatqm74p9r2p9vpdrg4yklgpx8faqrq39he0rqhtdnefeuy43mg8k"
authorization = "signam1qrkkr68fdyh87j2anfw4r5vpegmdqv8j3lp5y7234aqny0d4kr0rh92x4rs5p9fzutwz6aq4lsqs26s4mw8pgzrrckd5xw3dsqptvwqr9lq5wd"

[validator_account.tendermint_node_key]
pk = "tpknam1qplg8kvem78htnqsj34twn5hdd0yfsk8jp7r6yl2jlv72swnupm5y8drch7"
authorization = "signam1qrluc43gmjnl8gffcd8ev46q25u56rue0y0paywgagwjrs7vckzv6p8tq4n954xx85ljgq8d8hrus2hafl8pedsmhjw5yqatslysn4sxgj6nyl"

[validator_account.eth_hot_key]
pk = "tpknam1qypfrvyyrmc24ncteyvz9jkl6pqx7yz7f4j8em4lsug7utlu7luy79q78msxg"
authorization = "signam1q83echgeq60rmjtkgz0zvycy7e2z7jdsr0fdxfa3xzm04keqtdqpuq5k88tua7c5l472x85xyxk2t2wjcg8yz4uvm838yvec59tyn5h0qyjnsf3k"

[validator_account.eth_cold_key]
pk = "tpknam1qyp6g62hd4mmpzl0r8vvdct7mglrnwq9uxygxs0ss8kjk9y0efqe46c5h7lel"
authorization = "signam1q9gz2dpnj30fcr4seefeg3ew9f4njkaqrha7r49578acxt29yev8qd28wcgk2krg8a7qs6urql68zanhdauqv5ftufs3fkjj9gr5xr0yqya9s8wj"

[validator_account.metadata]
email = "n75pro@protonmail.com"
description = "Professional validator service"
website = "https://node75.org"
discord_handle = "shurinoff"
avatar = "https://raw.githubusercontent.com/the-node75/about-us/main/resources/logo_128x128.png"
name = "pro-nodes75"

[validator_account.signatures]
tpknam1qp5eqyc4k246jlkuzxzdrprla92e7p0urccuyjr7y096grgj7eydct4lxdu = "signam1qrlw8qqz5tm3djdlr7dr5c64fxcf8ra4tmwfw38ghjm3makxcyret0pkqszwkyp5fwrjn6a62xrdm4guhnp8daj5gh4e6zccv0gld3c26j8up9"

[[bond]]
source = "tnam1qyx57588ejm4ltfldr4kvftmcr8plkx7eykxkmsj"
validator = "tnam1qyx57588ejm4ltfldr4kvftmcr8plkx7eykxkmsj"
amount = "0.1"

[bond.signatures]
tpknam1qp5eqyc4k246jlkuzxzdrprla92e7p0urccuyjr7y096grgj7eydct4lxdu = "signam1qql702n47wy6ed2dj9a40jrep05ayrj3p3zmr8skk08fg3acyn8auvu73llk0nj68fwqk7ew9u57c2qy9jmyqn4kxl5qyem3mt9vfqqdzacxtm"
