# adding transaction for mrspir-validator

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qqyjgjhdek36tv0urrtxhz7pemvr96tz0ys86qqwrjfhw5ckana87ygmzry"]

[[validator_account]]
address = "tnam1q8hck7594xqw9dz35m8wwtgtvdxf4xn0mg908r8x"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.101.62:12656"

[validator_account.consensus_key]
pk = "tpknam1qz8ukqu0tj80g3v27azup3aeqdn77e27mvgkn83kj67qlker2gwlqku4576"
authorization = "signam1qqu5f6vrqzdlxmzrxmfef0g5g4z6w4ugskdj5mglyf0n5myadnurqapndgsgaepkjenyzrx9fwe2grleqmexuzrput9glauqcg5uy4gwwhewqc"

[validator_account.protocol_key]
pk = "tpknam1qr8qaza9v4dtx8sl5s28wtlfvgx4qtuynqzkysg5j9zftl968694jjp9w98"
authorization = "signam1qr46sxuq9zq5sgzwe7eee7a44r3rzlj069ctm9svjyeyuutg38xvmyw5hef7nj602wdjqts7s2773v8jctlex6mvafkdmw7qlzy5n0cvsgysr9"

[validator_account.tendermint_node_key]
pk = "tpknam1qzwrtc64vjuuxgcvmkaljyqcqnzmpfen0k83h77vr3k79xuv5332kwr378q"
authorization = "signam1qqqenz7y9jgvechegvvf588xa70l06nz0knsqp5555x07eu6c7nc0eydtraj9p0guucm5m0y4rg7nlsn4fwn5s3wr5rsrhe9e9a4v6c05g7478"

[validator_account.eth_hot_key]
pk = "tpknam1qypufdcrpum6lff58d4urhyzr7l43f42qcu3u7w5kkq72dhs9e6gp7s47ax7m"
authorization = "signam1q94pat63z2zkdlw0fjqt7s8p2lekm44yquupve24qp9lnhvtaua72ngz4gt7wu6snza8qu60lsjyklrlf7q3rzvdrergdgfeu95v0k7mqq6a7az4"

[validator_account.eth_cold_key]
pk = "tpknam1qypezw6qd5zkr0w7w0qm9grnht4rdpnl7qvhq5ymvxnk9hlpnhly25qg3p9h4"
authorization = "signam1q992wpe2df4hn34uvzuue00cj3jgqsp7la2ys25tm0qnl2eluflkcwlsdzt8x97hnm9u9czw75muj99wp8qy8386wzq2rqxad3p35269qq33395v"

[validator_account.metadata]
email = "hi@originstake.com"
description = "OriginStake is a trusted Proof-of-Stake infrastructure provider and validator to comfortably stake your coins and earn rewards with Namada."
website = "https://originstake.com"
discord_handle = "mrspir"
avatar = "https://raw.githubusercontent.com/OriginStake/ogs-media/main/Logo/PNG/OriginStake_Logo_1.png"
name = "OriginStake"

[validator_account.signatures]
tpknam1qqyjgjhdek36tv0urrtxhz7pemvr96tz0ys86qqwrjfhw5ckana87ygmzry = "signam1qpuln6xfw2wm5p5d7ujt2mgrucxnsplxzqkkmu0n7equyftnerlxxh028m74rw3mvu3vw495nzw5gt73alfhcz2lpjfsyv0285fdwsgqmv3wv9"


# adding transaction for validatorvn-validator

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qzj4svh5wvasuwdaau2sm5qs53c0tcu6u2wum7ly05et3w6q00j05ts0e4u"]

[[validator_account]]
address = "tnam1q8236gr76rrsluvq27j8mkma8u04hz0khszatckw"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.05"
net_address = "213.239.198.181:26656"

[validator_account.consensus_key]
pk = "tpknam1qzhnq08fa02yfgv6v7zg7uu4zx6ssc39mv6vndgmdx8dc40z95v7u5skrxt"
authorization = "signam1qrl7w5vk5486udr4jdqg9rlylnj9kc62f2qens6w290pacavg4jk3ucmn6ef7sqj5zjjur4xkz4ec4m70ulmy5z5xu0mwf9jthqdu3qzhjnq56"

[validator_account.protocol_key]
pk = "tpknam1qp97wn0l2aggzffeksradn309jjszyxz7gwzvch3h4kqw7xw68nn2nqh5qc"
authorization = "signam1qzu066h5lpcxkjgdmscxpn6lnsk9gzdq823dkxpc6us5fr83y5gg03l2kp7fxm59kl0r5cy6j5j45qzccay9pe0qjaupku99gl47lvsrpvc6gu"

[validator_account.tendermint_node_key]
pk = "tpknam1qpxaqpkhx75nu0wlusn7ca24tjdfvanp78azsqm97jxj8fw3nh2axrq4xts"
authorization = "signam1qz6le7sdq8rd3sm3cphk456v86v0juu00u8gtkfmxvawrqvcda58ge700w6dpxqmxxft094vdpw90m58f7q8gsrpra0sty0vuvudjdgqezrjlv"

[validator_account.eth_hot_key]
pk = "tpknam1qyptpmvn3exrf4hlzn6j0hhqtawr9wlrplawkcvxftl06qx0tytldlc3pqv45"
authorization = "signam1q9j03ve5eyfnhpx06ayyege8ykeyhy62u50yf6uy2nq96lunn3f5v6v6rm3l6qx6kjdrp64r9lchteed04emqz42mn7s996nj95vn2d9qysufy3t"

[validator_account.eth_cold_key]
pk = "tpknam1qyp77l23zy3t0qlf8ny7d4q92n9ra9jkwfuyr0dg05ct0zgaml40agq7crdc9"
authorization = "signam1q9rnuajdnwhvpaxexrk24vajd4jxjrdlghdf0g7vdyqvg9e46uw2ymqmu67vadxcllcjyd4ck0xlh8uwazaax97dyfmue6d3v0lqwnvpqqc4t27k"

[validator_account.metadata]
email = "admin@validatorvn.com"
description = "Trusted Proof-of-Stake validator & Tendermint chain service provider. Active ecosystem contributor, community manager & moderator"
website = "https://validatorvn.com"
discord_handle = "validatorvn"
avatar = "https://raw.githubusercontent.com/Dymioncloud/Logos/main/SG3ZfSyr_400x400.jpg"
name = "ValidatorVN"

[validator_account.signatures]
tpknam1qzj4svh5wvasuwdaau2sm5qs53c0tcu6u2wum7ly05et3w6q00j05ts0e4u = "signam1qz9vlsm5zgys46htj74y0a5pm6eka88yrlq73n96uy3z5m72kd0ptxjk5pgzsgpsy46p7ewed729vjrxl0vvp97ns5hmxr9m5l8l9wcwxe2puv"



# adding transaction for alxnode-validator

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qzdd0ndvtqylxvwj3e53utxcxspfusvrrfmznwhvxs0jaj48thgkwkgnjht"]

[[validator_account]]
address = "tnam1q8wldcr49mhm92a69fmf847d8rn48e6gcql2s4ya"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.05"
net_address = "198.244.176.55:26656"

[validator_account.consensus_key]
pk = "tpknam1qrpjpxmrh8w0cgfvtpqcqrv7r92ygcfzznzx7p02khdl98d9ltytuaneg3v"
authorization = "signam1qqluuhck68a6z0mtv02y7kfuu3tk2d9x436qdsenqwd5ssef4u28gjscg4prajgw8dem9wzgc9xxwh86ulu6jqh6fsd4wqthmyluhfsprs3wyv"

[validator_account.protocol_key]
pk = "tpknam1qzg2nhncanjn5nxmrq268ma692cdg4njzgg7rvm5ne2rw7se6kkwk8xmfvh"
authorization = "signam1qpf2ekzhx73fhda96q07cme6pm8hx5dyxq343k29n826eyd547p86y6emsalajxwhz6z6f0wuz6dnrpm2tgha2xggfng5j63shrfqcqz3xxkzr"

[validator_account.tendermint_node_key]
pk = "tpknam1qpu9dmuvl6jmm6j9gduy5vcgqee0ernhtw38dvhawpv0sxp28j46qmkk83a"
authorization = "signam1qqyyvhr4ee5lpv40e80gum2fegrhum3yl4fac09xsc0snn086yx99ucu9d2x8pmjhyvvz04cnj075pgs2kwmg2nm37dk0wfzptqcercxg57dzz"

[validator_account.eth_hot_key]
pk = "tpknam1qypag8hfdr4jxmwa8q9as40pmjttzgyrg69gun7mv78fdy56v5trxaq6g2547"
authorization = "signam1qympeq78q2pknesn0rjyenr84antltqqy8083fjdz4kj6082p2tsj5nss34nw7fmw4cjh94sw4cn7pt55q0s8z7n804zdm2jcqwp6g4hqyvcyfuw"

[validator_account.eth_cold_key]
pk = "tpknam1qyp88jg0x3aquu53mwa9rngn2q5gsgqt89v5dg5qmwfzg227dxu5vfsw5znhh"
authorization = "signam1qxzjvk7vq75ljdecfn2xjlsa67nnwej5kwlrdf4p0zn4jn8k3h2uqn070lxm23u2vgxgn0yygfva5add77q4gk6qaraw4tl6nrewnsqdqqv4u98j"

[validator_account.metadata]
email = "bitszn.com@gmail.com"
description = "Web3 development. Crypto staking. Low fees, high uptime"
website = "https://bitszn.com"
discord_handle = "alxbitszn"
avatar = "https://s3.amazonaws.com/keybase_processed_uploads/977f6ecd8916d7c354524703f8fb6305_360_360.jpg"
name = "bitszn"

[validator_account.signatures]
tpknam1qzdd0ndvtqylxvwj3e53utxcxspfusvrrfmznwhvxs0jaj48thgkwkgnjht = "signam1qpdylqckk63y0dl8e6nrqt0qd2jatmrdjp3w566dcq2qd40d9lf3eydk0dc7m7lrwzatj6xe5zuqztmuz6qlucnkzkd4r9amcvwqyegx5nnxyc"



# adding transaction for mcdaan-validator

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qqhjp8cjk442f4wfam6zf5pyjlzq5u6pp5cpf0xhvjlwj9ddkmnq6turgdy"]

[[validator_account]]
address = "tnam1q8sjkutd5kqwcc555wr77p9fjn66nuuqfuzzc3yc"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "142.132.135.125:24656"

[validator_account.consensus_key]
pk = "tpknam1qrkuhku5xze2g867097ne8vxh7qjc7tuag8s53p2zy7hssuk7lvfyhfhq7e"
authorization = "signam1qztlfq6df0u2ehvn73vaxpj97czw0udgrpj8algmjupjy4x44gn64vsh897qvhc3er3w86gv4nwh0jfxskfucqyr2eqdpmng5jgta3gqw835p5"

[validator_account.protocol_key]
pk = "tpknam1qz43lxlwxhmamr20wf3825etgfgalpnyuev7lprygk52x2yxm7hx6stlxfx"
authorization = "signam1qrsdgdtqal70pf29mx4c7ahzh7gygda00ckup2qnfrw6hphyjpk9dqthcccpjmkr0sfaqt8dtlx8cf6c7mldy8ype76nswxtn7zrcrgq68dxwd"

[validator_account.tendermint_node_key]
pk = "tpknam1qre7xfrvzvxrg7453q0u78ecup26sxjphw9qydrhvem5208w8addxtlevtc"
authorization = "signam1qzjatnzwuyennzpxygufprdx9prln2c8m2jgxmjtsnj8z8wjf6pvg4z39l92pmtyp0ghdslvtjj7m6va2a3qv8e2kxgjs08xxdc0z7ct623l6p"

[validator_account.eth_hot_key]
pk = "tpknam1qyp4p9wsg40hzgdygfurfg8jkjq5ya78eryr9enue694q9lvuzetkpggwg65t"
authorization = "signam1q9ctg6k7x4x376m4j5mg9gsesecyzhhjlqulc8n39r9t9dyqwhexg3s66ejxh4ccjftj7mfqah0cg6ddyj3swv38r23v7lzjs2acsyn3qq6g4wym"

[validator_account.eth_cold_key]
pk = "tpknam1qypfyy6s79cru85v35cwzt9r577astx3tsu339fy7jzhl2kv8y32dvgck2028"
authorization = "signam1q90rm09knnc5cgvpmu0egf5egqm9qzmd404y4g3a7629wuldj44u6sfrrgr4q29v43dzayk7t9ly62mzd2adwgch9qxpcxkv4lt8yhp3qyl20cfw"

[validator_account.metadata]
email = "support@mandragora.io"
description = "Stake and Chill Out!"
discord_handle = "danielmandragora"
avatar = "https://i.ibb.co/mzWB7tq/photo-2022-10-14-05-18-24.jpg"
name = "Mandragora"

[validator_account.signatures]
tpknam1qqhjp8cjk442f4wfam6zf5pyjlzq5u6pp5cpf0xhvjlwj9ddkmnq6turgdy = "signam1qzf3xruvc6djejzytqcsf7vfzzz4ln845fkra67yjh6kpl9lxhkufqs48u2vgvm7ah8tpmqzefnfm5at6dnswl5ty73nrmfdcj3w8vq8asade7"



# adding transaction for croutondigital-validator

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qz6t9x9qm3fh4a4g2vwyz9x3h8auyakpnruqzs94ukxr8yd2yzfvz4ka36c"]

[[validator_account]]
address = "tnam1qx64zytr93rjj23ztf32y2rnrxwlm9j6svyznxez"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "139.45.205.58:26656"

[validator_account.consensus_key]
pk = "tpknam1qpg4xpn38ww2gs0y48tx5gta4sktfvu8mruz94vvgeuq96q27u4p56u98pm"
authorization = "signam1qpffkppxe6c0d5msvglax0ekzjr40xnvlqplry8lwz5nqqzs5mhfqh0hhqkpslsvthzy2g9k2qprtjnggm6jrzprfagsaqsm7cjchncqpkku5a"

[validator_account.protocol_key]
pk = "tpknam1qp09duwy0hk0umxu284tjcu0yvc30etsfpxrmgz288kedgef6fhrx8nkgdq"
authorization = "signam1qrx77yzt6kmvf6ugly47v04g0l93hakmmdsqmajsxh04ajgqqug9lccrngxd8krjquedzxa3tuaqhs7w2wqmk42acx7aajz7tmzcpkcxmjnxza"

[validator_account.tendermint_node_key]
pk = "tpknam1qrwwyxqq009x8dpjxep3t29qeyk7n7l0qc40wz4xatdy3ledhwnk28vcdak"
authorization = "signam1qqjr4wwpjqfgyqhz5xwu4j39y7mlu9hntl03jv43ugq4ajt29ljqxksr8n9ev8h3ygxpwafgg0sry6n362raywe89npte532xmy3z0qxqwznat"

[validator_account.eth_hot_key]
pk = "tpknam1qyp3dxekyvan9a6psc8da3uuuxuddtw83zgcfpwtmvxjcyx27sw6gaq4ylkpk"
authorization = "signam1q8ec8xtnlmvctymmqq5gf7wwaxdqmqg664f9k8gna77gqa7ugdetyqzkv9t860q55dkm5fgpjngp3hzv4d7kq4fgkl8p6vl8lsyjs5aeqqnzpsua"

[validator_account.eth_cold_key]
pk = "tpknam1qypul462px9mcyu4kv4mfwd8pgpakc8djrmfu4lalrhghkljjcwy2lg4s040p"
authorization = "signam1q8zm3vxs8v7ftdw8ct4qrkslsf7537x72hasckmsl59lu0h7yjfvkhsfkj3pgrar30x56y0tsguppncceph4vnkrt327xuwyq3kt60m4qyh8r3jd"

[validator_account.metadata]
email = "official@crouton.digital"
description = "Your everyday crypto partner"
website = "https:/crouton.digital"
discord_handle = "ak32821"
avatar = "https://s3.amazonaws.com/keybase_processed_uploads/7b282adb3049558dba41acaf0e5c7f05_360_360.jpg"
name = "CroutonDigital"

[validator_account.signatures]
tpknam1qz6t9x9qm3fh4a4g2vwyz9x3h8auyakpnruqzs94ukxr8yd2yzfvz4ka36c = "signam1qpwq67a8e3g0mh3sffwlwrq3z7tpgkw42sca3np7lygdf8zzjjqlvt8pg3aze3j3szaz62juhcgmw8zrg79c23qu8zv82fcmthae2lgdg6hqy9"



# adding transaction for konsortech-validator

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qp04kmhvtuy5zhr4q6eh4rm5vry7s4vhmf4wzpyzvhp4leq59w00w0d8ysc"]

[[validator_account]]
address = "tnam1qxqj95as4g2hmkuj7uzvklwgch6tvqh8ay84m2jc"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "37.27.71.199:26656"

[validator_account.consensus_key]
pk = "tpknam1qzh5rqszkrgnu5ka73mq84td4kwt06c4a7r0zv82zvllqx9tz2gc2wh28cg"
authorization = "signam1qphypfxdc30lag9gztfzs5lm5eragtu8nga2y42upqrasewyznwq4d7584xk2pclt3dhj3juszv8u7w90dvnkjzhk73683tpkyrcz4qpjdrj7k"

[validator_account.protocol_key]
pk = "tpknam1qpdzdj9kmrnzd954gnr8zewy8r5j30st5e6mtn5peher03gmz8aq5xwp7rc"
authorization = "signam1qrx8h0c838yfma7ccjjvjvj67w6fd7y5nqy2equfjlftq4ljta0wn7dlg6tjf45lcyhka5jqc2l8xnp0v6srpztpf77gqspc5djla3gqdf5yv5"

[validator_account.tendermint_node_key]
pk = "tpknam1qqhdpcl30u7xm8rauyz8p3kegd8wefkp5rmx5zkws46pu0ean5c57cakt93"
authorization = "signam1qrzq9wlngxquzfcrwdr3zmlqldcvplgph2zjakd2ws9drraumkx4mtl4d5ktapm2wtjt97l5fzks760wta92s2ejz2tcnpt0fc73juq0h90z8y"

[validator_account.eth_hot_key]
pk = "tpknam1qypkh89m32w78ufcx8j537rhsxa85m6yvyvrfmmwka97tepeanuvdwsls2c6w"
authorization = "signam1qyd8ez4dvufg944sflhsuczk77rz3rc8x9t9qmq2k3hmqwt7z6g0y6qcazhdqvq6lwa6zlfhnqcu744eyxf6udcq2vkp4dg9urvlsmwlqq5kal2h"

[validator_account.eth_cold_key]
pk = "tpknam1qypz8kr40eyljqqn73p9j9fr8wtmvy7veadyzc7excnzp05e0a5za0ssudsxf"
authorization = "signam1qxacgesru0r8jkrc0z6tf2403sk05khqhrql8qgm4wmezffed9y6wxfqdpajtxa40kl82ygat932dvqdn4w8pjzqtq777hjrsnek4jgnqqgrd2x4"

[validator_account.metadata]
email = "validator@konsortech.xyz"
description = "Stake With Us ! Become Professional Stake Provider"
website = "https://konsortech.xyz"
discord_handle = "konsortech"
avatar = "https://ss-namada.konsortech.xyz/namada/profile/konsortech.jpg"
name = "KonsorTech"

[validator_account.signatures]
tpknam1qp04kmhvtuy5zhr4q6eh4rm5vry7s4vhmf4wzpyzvhp4leq59w00w0d8ysc = "signam1qq85vv4zkzn7nc0l6ufce5jwgu2mu52fy33vpjqh2cr9s87ml8p9avxfr3u35az2hm0ygz70u4l0u7gvztzsj6effkkcrennssp7gzs0mw5yx9"



# adding transaction for itrocket-team-validator

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qrt77k69kgahp0c9ajskf64z72amkvn3usagulqgluk6vdznxcpx29l9xnn"]

[[validator_account]]
address = "tnam1q99e0kqh32q6s3f3mr0ds772edyg7862jgj23fhh"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.36.231:26656"

[validator_account.consensus_key]
pk = "tpknam1qpp9usvn0080f3nnffhkdzv52czu4ykh8eawlw28we8a4jnsvakqyyhlus3"
authorization = "signam1qrh020ghlu7cpsp7m3whedgae4y33at0rvssm28a2l5twysj3et7wrecmju85ak3gm9rdvxpghrugk06gvqm8ujs9xm4shuusfe3dsc228hz6a"

[validator_account.protocol_key]
pk = "tpknam1qqv9hlsgrppkywkltpm6wntkkcdnzjy6fuqwvw005c6l3h5zdtcjsw65422"
authorization = "signam1qr83hzg7yvzl4n8xzd5xkz8ftle2jk45kzxtfgc6snjmsgklj3nj7u5hkhe08e6008m2er5wm9dwpprdgw4ffypznxuzy8ctwy5nnrsw3f0n75"

[validator_account.tendermint_node_key]
pk = "tpknam1qztp37zxkfp0wjh9rr7vz7tmzmvlld3k3nxcgvcznwkgnjlldu5mumd4a9y"
authorization = "signam1qrqcc56mfn8drdxwzdxc2hafpwpax2dshsfcg32wagy2thx64e2p6lqnz5l5m64c5dwhrsufzjlmqphvsppl5rxql3nd5jzavx9sl9qtel3wwy"

[validator_account.eth_hot_key]
pk = "tpknam1qypql7qk5qkzgpp5xpqeu2xmse7dpty3puv63c58qcwn7we5claxfjct7jllm"
authorization = "signam1qy6luys9lyydxd6cgyha68kxzyq03lzvqryc2mp0exr9f60pss7zxeg50xgskcl8nudrqcffqmqgtxx4ryp9ruru6vjdpa4q2zf5pnjrqqaddmd0"

[validator_account.eth_cold_key]
pk = "tpknam1qyppvu4ascq5uwkeddfj6ar5ft6rl0maad4qrkahy24lgdkqycsqt4cn3zv2j"
authorization = "signam1q9hfgxgw7vcgvltay6084vxyqkk43v9srh4cgxel75ff2yxelwk87vmpx9lw6eunnel7sqk6rl8qza7x8fss23s3j4xsqcuhx4kcfsxaqyvkym8e"

[validator_account.metadata]
email = "fastrpl@gmail.com"
description = "Trusted Validator & Interchain Utility Provider"
website = "https://itrocket.net/"
discord_handle = "itrocket"

[validator_account.signatures]
tpknam1qrt77k69kgahp0c9ajskf64z72amkvn3usagulqgluk6vdznxcpx29l9xnn = "signam1qp83efyj40d5sqgw8kf03yzsq7rjmk7kn5vuyzqsay98c6cdsyrn32uame6k2yetwu20ke92a9x48mmg3mafk82xrmzl9mdcnx3tcxc0xrh0mu"

